### ISSUE TITLE
Step 3: Present the solution

### ISSUE THREAD

**Issue by rondunn** [Microsoft/MCW-SQL-Server-hybrid-cloud#12]
The text says:

"Determine which table will be paired with your table before Step 3 begins."

Which is "your table"?

I think this should probably read, "Check the pairing of tables before step 3 begins."

**Comment by paulopsgility** [comment]
This is the official boilerplate for the MCW. 

These are built to be delivered at the C+E Bootcamps. This instruction is in reference to that delivery format but in general, that is how these are always delivered (students are grouped so they may work together), then the groups present to each other. 

I am leaving this as is, either way would work but since this is a boilerplate slide I don't want to change it across every MCW.
