### ISSUE TITLE
AdventureWorks is not available in the SQL server

### ISSUE THREAD

**Issue by Suraj2093** [microsoft/MCW-SQL-Server-hybrid-cloud#19]
In Exercise 1 Task 2, we are asked to select the AdventureWorks in SQL server Management studio and AdventureWorks is not available.

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @mwasham 
Michael/Paul - please review & advise.

**Comment by paulopsgility** [comment]
Fixed.
 
This was due to configuration drift in the Azure Marketplace image/setup causing the initial server configuration to take longer which then caused conflicts between the initialization process and our customer script extensions. I added some waits into our custom script extensions to allow the Microsoft's initial configuration to complete before we start modifying SQL settings etc.
